name: deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Manual deploy'
        default: 'dev'
        required: false

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy files via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          source: './apps/profile/.next, ./apps/profile/public, ./apps/profile/next.config.js, ./apps/profile/package.json'
          target: '~/'

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: 22
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            export NODE_DIR="$NVM_DIR/versions/node/v21.2.0/bin"

            pm2 stop prozhito-profile
            cd ~/apps/profile
            $NODE_DIR/npm install --omit=dev

            pm2 start -n prozhito-profile $NODE_DIR/npm -- run start
